import type { BuildManifest } from "./manifest.js";

/**
 * A minimal but schema-valid rich BuildManifest, used across packages/orchestrator-core and
 * apps/worker tests so every consumer of the manifest ingestion boundary exercises the same
 * realistic fixture rather than each hand-rolling a partial one.
 */
export function fixtureRichManifest(overrides: Partial<BuildManifest> = {}): BuildManifest {
  return {
    manifestId: "m-fixture",
    manifestVersion: "1.0.0",
    generatedAt: "2026-07-16T00:00:00.000Z",
    project: {
      title: "Searchable 3D parts library",
      brief: "Build a searchable parts library for a 3D printing business.",
      constraints: ["Must integrate with WordPress"],
      context: { existingStack: ["WordPress"], existingSystems: [], referenceNotes: [] },
      preferences: { strictness: 9, creativity: 9, detailLevel: 10, targetQualityScore: 92, maxRevisionCycles: 4 },
    },
    productDirection: {
      selectedDirection: "Reliable catalogue search",
      directionRationale: "Search is the core hook.",
      experienceThesis: "Finding the right part should feel fast and trustworthy.",
      creativePrinciples: ["Never a dead end", "Mobile first", "Trustworthy previews"],
      borrowedElements: [],
      signatureFeatures: [
        { id: "SF001", name: "Faceted search", whatMakesItMemorable: "Never a dead end", coreOrOptional: "core_identity" },
        { id: "SF002", name: "3D preview", whatMakesItMemorable: "Tangible before buying", coreOrOptional: "optional_novelty" },
        { id: "SF003", name: "Saved searches", whatMakesItMemorable: "Fast return visits", coreOrOptional: "core_identity" },
      ],
      discardedIdeas: [{ idea: "Shape-similarity search", reasonDiscarded: "Too costly for v1" }],
      designRisks: [],
      memorabilityTest: ["Would a user call this 'the search that always finds something'?", "Would they remember the preview?", "Would they recall a saved search?"],
    },
    users: [
      {
        id: "U001",
        name: "Hobbyist buyer",
        description: "A customer browsing parts on a phone in a hurry.",
        goals: ["Find a compatible part fast"],
        frustrations: [],
        technicalConfidence: "medium",
        primaryDevice: "mobile",
        accessibilityNeeds: [],
      },
    ],
    experiencePrinciples: ["Search must never return a dead end", "Every preview builds confidence", "Mobile is primary"],
    journeys: [
      {
        id: "J001",
        name: "First-time part search",
        actor: "Hobbyist buyer",
        trigger: "Buyer needs a replacement part",
        entryPoint: "Homepage search bar",
        assumptions: [],
        steps: [
          { step: 1, location: "Homepage", userThought: "I need this part", userAction: "Types a query", systemResponse: "Shows suggestions", featureIds: ["F001"] },
        ],
        decisionPoints: [],
        emotionalCurve: [],
        confusionRisks: [],
        recoveryPaths: [{ failure: "No results found", recoverySteps: ["Show broader suggestions"], worstCase: "Buyer leaves" }],
        completionSignal: "Buyer opens a part detail page",
        returnPath: "Back button returns to results",
        instrumentation: [],
      },
    ],
    features: [
      {
        id: "F001",
        parentId: null,
        name: "Search",
        summary: "Faceted search across the parts catalogue.",
        purpose: "Let buyers find a compatible part quickly.",
        userValue: "Fast, confident discovery.",
        businessValue: "Higher conversion.",
        actors: ["Buyer"],
        entryPoints: ["Homepage search bar"],
        prerequisites: [],
        primaryFlow: [{ step: 1, actor: "Buyer", action: "Searches", systemResponse: "Shows results", visibleOutcome: "Results list" }],
        alternateFlows: [],
        states: [],
        dataRequirements: [],
        permissions: [],
        analyticsEvents: [],
        failureModes: [],
        recoveryBehaviour: [],
        mobileBehaviour: ["Filters collapse into a bottom sheet on mobile"],
        accessibilityBehaviour: ["Results announced via ARIA live region"],
        privacyConsiderations: [],
        dependencies: [],
        acceptanceCriteria: [{ id: "AC001", criterion: "Search returns results within 300ms for 5000+ parts", measurement: "p95 latency under load test" }],
        testScenarios: [{ id: "TS001", name: "Search returns matches", given: "A catalogue of 5000 parts", when: "A buyer searches a known part name", then: "The part appears in the top 3 results", kind: "integration" }],
        openDecisions: [],
      },
    ],
    designSystem: {
      visualConcept: "Industrial-premium",
      visualPrinciples: ["Scanability over decoration", "Imagery is the largest element", "Visible focus states"],
      visualAntiPatterns: ["No decorative motion on loading", "No hidden filters", "No grey-on-grey text"],
      layoutSystem: {
        description: "12-column responsive grid.",
        contentMaxWidth: "1180px",
        wideLayoutMaxWidth: "1440px",
        gridColumns: 12,
        mobileGutter: "16px",
        tabletGutter: "24px",
        desktopGutter: "32px",
        breakpoints: [{ name: "mobile", minWidth: "0px" }, { name: "desktop", minWidth: "1024px" }],
      },
      typographySystem: { headingFont: "Inter", bodyFont: "Inter", baseSizePx: 16, scaleRatio: 1.25, lineHeights: { body: 1.5 }, weightRules: ["Headings 600"] },
      spacingSystem: { baseUnitPx: 4, spacingScale: [4, 8, 16, 32], usageRules: ["Card padding uses 16px"] },
      colourRoles: [
        { role: "primary", value: "#1D4ED8", usage: "Primary actions", contrastNotes: "4.5:1" },
        { role: "surface", value: "#FFFFFF", usage: "Cards", contrastNotes: "Base" },
        { role: "danger", value: "#DC2626", usage: "Errors", contrastNotes: "4.5:1" },
        { role: "text-secondary", value: "#4B5563", usage: "Metadata", contrastNotes: "4.5:1" },
      ],
      componentDensity: "Comfortable",
      shapeLanguage: { cornerRadii: [4, 8], borderRules: [], elevationRules: [] },
      iconography: { style: "Outlined", strokeWidth: "1.5px", sizes: [16, 24], library: "Lucide" },
      motionSystem: { personality: "Quick and functional", microInteractionDurationMs: [120, 180], panelTransitionDurationMs: [220, 280], easingRules: [], forbiddenMotion: [] },
      responsiveRules: [{ breakpoint: "mobile", rule: "Filters collapse" }, { breakpoint: "desktop", rule: "Filters visible" }],
      darkModeRules: [],
      reducedMotionRules: ["Disable transitions when prefers-reduced-motion is set"],
      loadingPresentation: ["Skeleton rows"],
      emptyStatePersonality: ["Offer a concrete next action"],
      errorPresentation: ["Errors include a retry action"],
      screenshotReviewChecklist: ["Contrast 4.5:1", "Touch targets 44px", "Focus visible", "Empty/error distinct", "Imagery not cropped"],
    },
    architecture: {
      systemContext: "A search-first parts catalogue integrated with WordPress.",
      architecturalStyle: "Modular monolith with a dedicated search index.",
      architecturalPrinciples: ["Search scales independently", "One ingestion pipeline", "Every API has one owner"],
      modules: [{ id: "M001", name: "Search Service", responsibility: "Serves search queries", boundaries: "Owns the index", dependsOn: ["Catalogue Ingestion"], exposedInterfaces: ["GET /search"] }],
      dataModels: [{ name: "Part", purpose: "A printable part", fields: [{ name: "id", type: "string", required: true, notes: "Primary key" }], relationships: [], indexes: [], retention: "indefinite" }],
      APIs: [{ id: "API001", method: "GET", path: "/search", purpose: "Search parts", requestShape: "{ q: string }", responseShape: "{ results: Part[] }", errors: [], authRequired: false, owner: "Search Service" }],
      events: [],
      stateOwnership: [],
      backgroundJobs: [],
      cachingStrategy: [],
      authentication: { approach: "None required for public search", details: [] },
      authorization: { approach: "Role-based for admin", roles: ["buyer", "admin"], rules: [] },
      validationStrategy: ["All input validated at the edge"],
      errorHandlingStrategy: ["Structured error codes"],
      observability: { logging: [], metrics: [], alerts: [] },
      securityControls: [{ threat: "Query injection", control: "Parameterized queries", layer: "Search Service" }],
      deploymentModel: { approach: "Containerized services", environments: ["staging", "production"], steps: [] },
      migrationStrategy: { approach: "Expand-and-contract", steps: ["Add nullable columns", "Backfill", "Enforce constraints"] },
      backupStrategy: { approach: "Nightly snapshots", cadence: "nightly", restoreTest: "Monthly drill" },
      rollbackStrategy: { approach: "Blue-green deploy", steps: ["Route back to previous version"] },
      testStrategy: { levels: ["unit", "integration"], tooling: ["Vitest"], coverageExpectations: "Critical paths covered" },
      performanceTargets: [{ metric: "search p95 latency", target: "under 300ms", measurement: "Load test" }],
      scalabilityRisks: [],
      architectureDecisions: [
        { id: "ADR001", decision: "Use a dedicated search index", rationale: "Faceted search needs it", alternativesConsidered: ["Direct SQL search"], tradeoffs: ["Adds an ingestion pipeline"], failureModes: [], futureExtension: "Index can later support shape-similarity search." },
        { id: "ADR002", decision: "Public search requires no auth", rationale: "Anonymous discovery surface", alternativesConsidered: ["Require account"], tradeoffs: ["No personalization"], failureModes: [], futureExtension: "Add optional personalization for logged-in users." },
        { id: "ADR003", decision: "Cache popular results", rationale: "Reduce index load", alternativesConsidered: ["No cache"], tradeoffs: ["Invalidation complexity"], failureModes: [], futureExtension: "Move to a CDN-edge cache for global buyers." },
      ],
    },
    edgeCases: {
      findings: [{ id: "EC001", category: "behaviour", scenario: "Empty catalogue", trigger: "No parts indexed", expectedBehaviour: "Show empty state", currentGap: "None", severity: "medium", affectedFeatures: ["F001"], requiredMitigation: "Define empty state" }],
      systemicRisks: [],
      highestRiskAreas: ["Zero-result recovery"],
      missingRecoveryPatterns: [],
      requiredPlanChanges: [],
    },
    scope: {
      classifications: [
        { itemId: "F001", itemName: "Search", scopeClass: "essential", rationale: "Core value proposition.", cheaperAlternative: null, isSignatureElement: true },
      ],
      minimumCompleteProduct: ["F001"],
      recommendedFirstRelease: ["F001"],
      premiumRelease: [],
      experiments: [],
      deferredItems: [],
      rejectedItems: [],
      sequencingRationale: ["Search must ship first; it is the core hook."],
      scopeRisks: [],
    },
    implementationPlan: {
      phases: [{ id: "P1", name: "Foundation search", goal: "Ship faceted search", includedFeatureIds: ["F001"], exitCriteria: ["Search returns results within 300ms p95"] }],
      workstreams: [{ id: "W1", name: "Search platform", description: "Search indexing and query API", phaseIds: ["P1"] }],
      dependencyGraph: [{ from: "Catalogue ingestion", to: "Search Service", reason: "Search indexes ingested data" }],
      proposedRepositoryStructure: [{ path: "apps/search-service", kind: "directory", purpose: "Search indexing and query API" }],
      fileResponsibilities: [],
      databaseChanges: [{ id: "DB1", change: "Add parts table with search indexes", phaseId: "P1", reversible: true }],
      apiBuildOrder: ["GET /search"],
      uiBuildOrder: ["Search bar", "Search results list"],
      testBuildOrder: ["Search API integration tests"],
      releaseCheckpoints: [{ id: "RC1", name: "Search MVP launch", afterPhaseId: "P1", verification: ["Load test passes"] }],
    },
    qualityRequirements: {
      performance: ["Search p95 latency under 300ms"],
      accessibility: ["Search results announced via ARIA live region"],
      security: ["No raw query strings passed to the search backend"],
      reliability: [],
      compatibility: [],
    },
    definitionOfDone: [
      { id: "DOD1", item: "Search returns results within performance targets", verification: "Load test report" },
      { id: "DOD2", item: "All UI states defined for search are implemented", verification: "Manual QA" },
      { id: "DOD3", item: "Accessibility checklist passes for search", verification: "Accessibility audit" },
      { id: "DOD4", item: "Offline recovery state is implemented", verification: "Manual QA" },
      { id: "DOD5", item: "Search API documented via OpenAPI", verification: "OpenAPI schema review" },
    ],
    unresolvedDecisions: [],
    assumptions: [],
    traceability: {
      entries: [
        { sourceRequirement: "Must work well on mobile", origin: "brief", featureIds: ["F001"], journeyIds: ["J001"], architectureIds: ["ADR001"], acceptanceCriteriaIds: ["AC001"], testScenarioIds: ["TS001"] },
      ],
      untracedItems: [],
    },
    planGate: {
      decision: "passed",
      findings: [],
      errorCount: 0,
      warningCount: 0,
      noticeCount: 0,
      coverage: {
        essentialFeaturesWithAcceptanceCriteria: 1,
        essentialFeaturesWithTestScenarios: 1,
        requirementsWithTraceability: 1,
        featuresAssignedToImplementationPhase: 1,
      },
      adjudicationUsed: false,
      summary: "The compiled manifest is internally consistent, fully referenced, and implementation-ready with no findings.",
    },
    ...overrides,
  };
}
